// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAwWnM2XggK6LhbVRiOhr5lNEXph5XrgE',
    appId: '1:333282399082:web:91de6871656c70dc7acb13',
    messagingSenderId: '333282399082',
    projectId: 'patentify-35ff3',
    authDomain: 'patentify-35ff3.firebaseapp.com',
    storageBucket: 'patentify-35ff3.firebasestorage.app',
    measurementId: 'G-36YHBH7XNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAob3RQIda4eUyBG0p1CCMT37PI50C3124',
    appId: '1:333282399082:android:5fba21c8236424a67acb13',
    messagingSenderId: '333282399082',
    projectId: 'patentify-35ff3',
    storageBucket: 'patentify-35ff3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIP1wcM14XNTtMo6oGKEKfV3N4ZfDJPjM',
    appId: '1:333282399082:ios:03fa4a83d076988d7acb13',
    messagingSenderId: '333282399082',
    projectId: 'patentify-35ff3',
    storageBucket: 'patentify-35ff3.firebasestorage.app',
    iosClientId: '333282399082-7t47353a7n8gjelvdqfh5pled3cu0tvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.patentify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAwWnM2XggK6LhbVRiOhr5lNEXph5XrgE',
    appId: '1:333282399082:web:04b1a6e5f3c116397acb13',
    messagingSenderId: '333282399082',
    projectId: 'patentify-35ff3',
    authDomain: 'patentify-35ff3.firebaseapp.com',
    storageBucket: 'patentify-35ff3.firebasestorage.app',
    measurementId: 'G-FN3TG0P8CE',
  );

}